## Learning Objectives

### 1. Python Lists vs. NumPy Arrays
- Understand the structural and performance differences between Python lists and NumPy arrays.

### 2. Memory Structure of NumPy Arrays
- Learn how NumPy arrays store homogeneous data in contiguous memory, enabling efficient numerical computation.

### 3. Basic NumPy Array Creation and Attributes
- `np.array`
- `np.zeros`
- `np.arange`


In [1]:
import numpy as np

### 1. Python Lists vs. NumPy Arrays

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])

In [5]:
arr_2d1 = np.arange(26, 51).reshape(5, 5)

In [6]:
print("1D Array:", arr_1d)
print("Shape:", arr_1d.shape)
print("Dtype:", arr_1d.dtype)

1D Array: [1 2 3 4 5]
Shape: (5,)
Dtype: int64


In [7]:
print("\n2D Array:\n", arr_2d)
print("Shape:", arr_2d.shape)
print("Dtype:", arr_2d.dtype)


2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Shape: (5, 5)
Dtype: int64


In [8]:
print("\n2D Array:\n", arr_2d1)
print("Shape:", arr_2d1.shape)
print("Dtype:", arr_2d1.dtype)


2D Array:
 [[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
Shape: (5, 5)
Dtype: int64


### 2. Memory Structure of NumPy Arrays

In [ ]:
# 1 ms = 10e-3 s
python_list = list(range(1, 1000001))
%timeit sum(python_list)

20.4 ms ± 1.93 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
# 1 μs = 10e-6 s
numpy_list = np.arange(1, 1000001)
%timeit np.sum(numpy_list)

708 μs ± 65.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### 3. Basic NumPy Array Creation and Attributes

In [13]:
zeros = np.zeros((3, 4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
range_arr = np.arange(0, 12, 2)
print(range_arr)
print(range_arr.reshape(2, 3))

[ 0  2  4  6  8 10]
[[ 0  2  4]
 [ 6  8 10]]


In [19]:
linspace_arr = np.linspace(0, 7, 5)
print(linspace_arr)

[0.   1.75 3.5  5.25 7.  ]
